name: tests

on:
  push:
    branches: [ master ]

jobs:
  run_tests:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - name: Use Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
    - name: Run tests
      run: xcodebuild test -scheme MusicalRoomUITests -project MusicalRoom.xcodeproj -destination 'platform:iOS Simulator, id:DDC5AC8E-8888-43AE-B034-9942BFEDAA32, OS:15.2, name:iPhone 12' | xcpretty && exit ${PIPESTATUS[0]}
